### ISSUE TITLE
Failed to start a node

### ISSUE THREAD

**Issue by So1m** [near/stakewars-iv#65]
### Overview
Got error when starting node:

 ERROR runtime: Failed to check if a state snapshot exists err=STATE_SNAPSHOT_KEY thread 'main' panicked at chain/client/src/client_actor.rs:219:6: called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: 513Udd1hWDBnU9pNxt8thBsXGQ53ja9gLHsEeGiv34Pe"))

### Impact
Node doesn't start

## Reproduction steps
Fresh VM with Ubuntu 22.04.

1. Builded neard:
cargo build --package neard --features statelessnet_protocol --release
2. Downloaded latest snapshot from S3
aws s3 --no-sign-request cp s3://near-protocol-public/backups/statelessnet/rpc/latest .
latest=$(cat latest)
aws s3 --no-sign-request cp --recursive s3://near-protocol-public/backups/statelessnet/rpc/$latest .
3. Started node
cd ~/nearcore/
./target/release/neard --home ~/.near run

After that node start sync latest data. After successful sync i've received:
ERROR client: Received an invalid block during state sync err=DBNotFoundErr("epoch block: GbPLXvRBKZCRsbYzG3JzYnDLMCPZp8wWw2CkUpebiBau") block_hash=CDcPENNABVnf5tZ3oobT5CczLaNPc819je6qXRvNUv9J

4. Attempted to restart the node.

Got error:

ERROR runtime: Failed to check if a state snapshot exists err=STATE_SNAPSHOT_KEY thread 'main' panicked at chain/client/src/client_actor.rs:219:6: called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: 513Udd1hWDBnU9pNxt8thBsXGQ53ja9gLHsEeGiv34Pe"))

6. Replace  "state_sync_enabled": true, to  "state_sync_enabled": false,
Still got the same error.

**Comment by So1m** [comment]
Hey!

Thanks for the response ;)

I've removed data, repeated step 6 -> 2 -> 3 and node seems to be working :)
